--sql CREATE TABLE TO STORE DATA FROM r.univar
-- USE THIS IN ORDER TO IMPORT THE ORIGINAL CSV GENERATED BY r.univar (ALL ATTRIBUTES)
DROP TABLE IF EXISTS :vSCHEMA.:vNAME;
CREATE TABLE :vSCHEMA.:vNAME (
pa text,
non_null_cells integer,
null_cells bigint,
min double precision,
max double precision,
range double precision,
mean double precision,
mean_of_abs double precision,
stddev double precision,
variance double precision,
coeff_var double precision,
sum numeric(20,4),
sum_abs numeric(20,4)
); 
