#!/bin/bash
# PARAMETERS FOR GFC PREPROCESSING

## SET VARIABLES
NCORES=56

base_indir="/spatial_data/Original_Datasets/GLOBAL_FOREST_CHANGE/archives/2023_V1.11" # REMEMBER TO UPDATE THIS STRING ACCORDING TO THE VERSION USED
base_outdir="/spatial_data/Derived_Datasets/RASTER/GFC/2023_V1.11" # REMEMBER TO UPDATE THIS STRING ACCORDING TO THE VERSION USED
rootstring="Hansen_GFC-2023-v1.11_"						# REMEMBER TO UPDATE THIS STRING ACCORDING TO THE VERSION USED
temp_dir="/spatial_data/Derived_Datasets/RASTER/temp"  	# CREATED BY THE SCRIPT

TREE_LIST_FILE=${base_indir}"/treecover_filelist.txt" 	# MUST EXIST BEFORE RUNNING THE SCRIPT
GAIN_LIST_FILE=${base_indir}"/gain_filelist.txt" 		# MUST EXIST BEFORE RUNNING THE SCRIPT
LOSS_LIST_FILE=${base_indir}"/lossyear_filelist.txt" 	# MUST EXIST BEFORE RUNNING THE SCRIPT

## PARAMETERS FOR GRASS DB
DATABASE="/globes/USERS/GIACOMO/GRASSDATA" 						# CAUTION: MUST EXIST BEFORE RUNNING THE SCRIPTS!
LOCATION_LL="WGS84LL"											# CAUTION: MUST EXIST BEFORE RUNNING THE SCRIPTS!
LOCATION_MO="MOLLWEIDE"											# CAUTION: MUST EXIST BEFORE RUNNING THE SCRIPTS!
PERMANENT_MAPSET_LL="${DATABASE}/${LOCATION_LL}/PERMANENT/"
PERMANENT_MAPSET_MO="${DATABASE}/${LOCATION_MO}/PERMANENT/"