--sql CREATE TABLE TO STORE DATA FROM r.stats
-- USE THIS IN ORDER TO IMPORT THE ORIGINAL CSV GENERATED BY r.stats WHEN TWO RASTERS ARE ANALYSED 
--(for example land cover change) 


DROP TABLE IF EXISTS :vSCHEMA.:vNAME;
CREATE TABLE :vSCHEMA.:vNAME (
qid integer,
cid integer,
lc_1995 integer,
lc_2015 integer,
area_m2 double precision
);


