--sql CREATE TABLE TO STORE DATA FROM r.stats
-- USE THIS IN ORDER TO IMPORT THE ORIGINAL CSV GENERATED BY r.stats WHEN ONLY ONE RASTER IS ANALYSED 
--(for example lpd,ghs_built, etc.)
-- NOT TO BE USED FOR MULTIPLE RASTER ANALYSIS SUCH land cover change

DROP TABLE IF EXISTS :vSCHEMA.:vNAME;
CREATE TABLE :vSCHEMA.:vNAME (
qid integer,
cid integer,
area_m2 double precision
);


