#!/bin/bash
##PROCESS GEBCO MARINE PAs (MHDI)

echo "-----------------------------------------------------------------------------------"
echo "--- Script $(basename "$0") started at $(date)"
echo "-----------------------------------------------------------------------------------"

startdate=`date +%s`

set -o nounset  # Break if a variable is unset

# READ VARIABLES FROM CONFIGURATION FILE
SERVICEDIR="/globes/processing_current/servicefiles"
source ${SERVICEDIR}/wdpa_processing.conf

GEBCO="gebco2026@CONRASTERS"

## Derived variables
LOCATION_LL_PATH=${DATABASE}/${LOCATION_LL}
PERMANENT_LL_MAPSET=${DATABASE}/${LOCATION_LL}"/PERMANENT"
NCORES=48

## PAs TO BE ANALYZED ************************CHECK/EDIT IT BEFORE RUN
PA_LIST_FILE=${SERVICEDIR}/${pa_ma_list}.txt

## GRASS parallel processing block
((NTILES=${NCORES}-1))
((ALLPAS=$(cat ${PA_LIST_FILE} | wc -l)+1))
((TILESIZE=(${ALLPAS}+(${NCORES}-1))/${NCORES}))   #TILESIZE is rounded up in order to ensure that [last tile + TILESIZE] is always > ALLPAS" 
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    TIL=${TIL}
    TEMPORARY_MAPSET=geb_${TIL}
    TEMPORARY_MAPSET_PATH=${LOCATION_LL_PATH}/${TEMPORARY_MAPSET}
    #Build temporary Mapset name
    grass ${PERMANENT_LL_MAPSET} --exec g.mapset --q -c --overwrite mapset=${TEMPORARY_MAPSET}
    echo "./slave_mhdi_pa.sh ${TIL} ${TEMPORARY_MAPSET_PATH} ${RESULTSPATH} ${TILESIZE} ${PA_LIST_FILE} ${PA_MAPSET} ${GEBCO}"
done | parallel -j ${NCORES}

echo "GRASS Processing completed, now post-processing results..."

## merge results
cat ${RESULTSPATH}/pa_gebco_tile*.csv >> ${RESULTSPATH}/pa_marine_gebco.csv

wait

## delete mapsets and intermediate results
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    rm -rf ${LOCATION_LL_PATH}/geb_${TIL}
    rm -f ${RESULTSPATH}/*_tile${TIL}.csv
done

## SECOND CYCLE: REPEAT PROCESSING FOR PAs NOT PROCESSED DURING FIRST CYCLE
cat ${RESULTSPATH}/pa_marine_gebco.csv | awk '{print $1}' FS="|">./gebco_actually_done.csv
 comm -23 <(sort ${PA_LIST_FILE}) <(sort ./gebco_actually_done.csv)>./gebco_to_be_repeated.csv

# MISSING_PA_LIST="gebco_to_be_repeated.csv"
# for PA in $(cat ${MISSING_PA_LIST})
    # do
    # grass ${PERMANENT_LL_MAPSET} --exec ./dyn/process_gebco_${PA}.sh
# done

# cat ${RESULTSPATH}/pa_gebco_tile*.csv >> ${RESULTSPATH}/pa_marine_gebco.csv

## REMOVE INVALID VALUES FROM CSV GENERATED BY r.univar
sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/pa_marine_gebco.csv
mv ${RESULTSPATH}/pa_marine_gebco.csv.bak ${RESULTSPATH}/pa_marine_gebco.orig
sed -i.bak 's/-nan//g; s/nan//g' ${RESULTSPATH}/pa_marine_gebco.csv
sed -i 's/nan/0/g' ${RESULTSPATH}/pa_marine_gebco.csv
# replace strange number (grass bug) with 0
sed -i 's/-1.79769313486232e+308/0/g' ${RESULTSPATH}/pa_marine_gebco.csv

rm -f ${RESULTSPATH}/*.bak

echo "Post-processing completed, now cleaning intermediate results..."

## delete intermediate results
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
    do
    rm -f ${RESULTSPATH}/*_tile${TIL}.csv
done
rm -f ./*actually_done.csv
#rm -f ./*to_be_repeated.csv

## delete dynamic scripts
rm -f dyn/process_gebco*.sh

enddate=`date +%s`
runtime=$(((enddate-startdate) / 60))

echo "---------------------------------------------------------------------------------------"
echo "Script $(basename "$0") ended at $(date)"
echo "---------------------------------------------------------------------------------------"
echo "Stats on PA marine and gebco computed in "${runtime}" minutes using "${NCORES}" cores "
echo "---------------------------------------------------------------------------------------"
exit
