#!/bin/bash
##PROCESS SEA SURFACE TEMPERATURE

startdate=`date +%s`

set -o nounset  # Break if a variable is unset

# READ VARIABLES FROM CONFIGURATION FILE
SERVICEDIR="/globes/processing_current/servicefiles"
source ${SERVICEDIR}/wdpa_processing.conf

# Derived variables
LOCATION_LL_PATH=${DATABASE}/${LOCATION_LL}
PERMANENT_LL_MAPSET=${DATABASE}/${LOCATION_LL}"/PERMANENT"
SST_LL_MAPSET=${DATABASE}/${LOCATION_LL}"/NASA_SST"
PA_LIST_FILE=${SERVICEDIR}/${pa_ma_list}".txt"

NCORES=36

## GRASS parallel processing block
((NTILES=${NCORES}-1))
((ALLPAS=$(cat ${PA_LIST_FILE} | wc -l)+1))
((TILESIZE=(${ALLPAS}+(${NCORES}-1))/${NCORES}))   #TILESIZE is rounded up in order to ensure that [last tile + TILESIZE] is always > ALLPAS" 
for TIL in $(for i in $(eval echo {0..$NTILES}); do ((start=${TILESIZE}*$i)); echo -n $start" "; done)
	do
	TIL=${TIL}
	TEMPORARY_MAPSET=sst_${TIL}
	TEMPORARY_MAPSET_PATH=${LOCATION_LL_PATH}/${TEMPORARY_MAPSET}
	#Build temporary Mapset name
	grass ${PERMANENT_LL_MAPSET} --exec g.mapset --q -c --overwrite mapset=${TEMPORARY_MAPSET}
	echo "./slave_nasa_sst_pa.sh ${TEMPORARY_MAPSET_PATH} ${RESULTSPATH} ${TILESIZE} ${PA_LIST_FILE} ${PA_MAPSET} ${TIL}"
done | parallel -j ${NCORES}

wait

echo "GRASS Processing completed, now post-processing results..."

## REMOVE INVALID VALUES FROM CSV GENERATED BY r.univar
for MONTH in $(eval echo {01..12})
    do
	cat ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}_tile*.csv >> ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.csv
    sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.csv
	mv ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.csv.bak ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.orig
	sed -i.bak 's/-nan//g; s/nan//g' ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.csv
	sed -i 's/-1.79769313486232e+308/0/g' ${RESULTSPATH}/pa_nasa_sst_avg_${MONTH}.csv

    cat ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}_tile*.csv >> ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.csv
	sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.csv
	mv ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.csv.bak ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.orig
	sed -i.bak 's/-nan//g; s/nan//g' ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.csv
	sed -i 's/-1.79769313486232e+308/0/g' ${RESULTSPATH}/pa_nasa_sst_max_${MONTH}.csv

    cat ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}_tile*.csv >> ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.csv
	sed -i.bak 's/non_null_cells|null_cells|min|max|range|mean|mean_of_abs|stddev|variance|coeff_var|sum|sum_abs|first_quart|median|third_quart|perc_90/|||||||||||||||/g' ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.csv
	mv ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.csv.bak ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.orig
	sed -i.bak 's/-nan//g; s/nan//g' ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.csv
	sed -i 's/-1.79769313486232e+308/0/g' ${RESULTSPATH}/pa_nasa_sst_min_${MONTH}.csv
done

rm -f ${RESULTSPATH}/*.bak
rm -f ./dyn/process_sst*.sh
rm -f ${RESULTSPATH}/*tile*.csv

enddate=`date +%s`
runtime=$(((enddate-startdate) / 60))

echo "---------------------------------------------------------------------------------------"
echo "Script $(basename "$0") ended at $(date)"
echo "---------------------------------------------------------------------------------------"
echo "Stats on PAs and SST computed in "${runtime}" minutes using "${NCORES}" cores "
echo "---------------------------------------------------------------------------------------"
exit

